// src/App.jsx
import { useState, useEffect, useRef, useCallback } from "react";
import AuthPage from "./pages/AuthPage";
import { useAuth } from "./context/AuthContext";
import AIPanel from "./components/AIPanel";
import Loader from "./components/Loader";

const API_BASE   = import.meta.env.VITE_API_BASE || "http://localhost:8000";
const RESOLUTIONS = ["1080p", "1440p", "4K"];

const INTENTS = [
  { label: "Gaming",         icon: "🎮", description: "High FPS, smooth gameplay" },
  { label: "FPS / Competitive", icon: "🎯", description: "240Hz+, low latency" },
  { label: "Video Editing",  icon: "🎬", description: "4K rendering, fast exports" },
  { label: "3D / CAD",       icon: "📐", description: "Blender, AutoCAD, rendering" },
  { label: "Streaming",      icon: "📡", description: "Game + stream simultaneously" },
  { label: "Programming",    icon: "💻", description: "Compilation, VMs, containers" },
  { label: "Office / Study", icon: "📚", description: "Productivity, multitasking" },
];

const BUDGET_PRESETS = [
  { label: "30K",  value: 30000  },
  { label: "50K",  value: 50000  },
  { label: "80K",  value: 80000  },
  { label: "1.2L", value: 120000 },
  { label: "2L",   value: 200000 },
];

const COMP_COLORS = {
  cpu: "#f0a500", gpu: "#7c6af7", motherboard: "#3bbfef",
  ram: "#64dc82", storage: "#ef6464", psu: "#ff9f4b", case: "#a78bfa",
};

const COMP_ICONS = {
  cpu: "⚙️", gpu: "🎮", motherboard: "🔌",
  ram: "🧠", storage: "💾", psu: "⚡", case: "🗄️",
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function formatINR(n) {
  return new Intl.NumberFormat("en-IN", {
    maximumFractionDigits: 0,
    minimumFractionDigits: 0,
  }).format(n);
}

function getBuildText(result) {
  const c     = result?.build?.components || {};
  const lines = ["🚀 RIGCRAFT BUILD RECOMMENDATION", "═".repeat(50), ""];
  if (result.intent) lines.push(`🎯 Use Case    : ${result.intent}`);
  if (result.tier)   lines.push(`📊 Tier        : ${result.tier}`);
  lines.push("");

  ["cpu", "gpu", "motherboard", "ram", "storage"].forEach((k) => {
    if (c[k]) {
      const price = c[k].Price || c[k].price || 0;
      lines.push(`${COMP_ICONS[k]} ${k.toUpperCase().padEnd(12)}: ${c[k].Name || c[k].name}`);
      lines.push(`   ${" ".padEnd(12)}  ₹${formatINR(price)}`);
      lines.push("");
    }
  });

  if (result.psu_wattage)  lines.push(`⚡ PSU         : ${result.psu_wattage}`);
  if (result.cabinet_type) lines.push(`🗄️ Cabinet     : ${result.cabinet_type}`);
  lines.push("");
  if (result.build?.total_price) {
    lines.push(`💰 TOTAL       : ₹${formatINR(result.build.total_price)}`);
    lines.push(`   (All prices include estimated taxes)`);
  }
  lines.push("", "─".repeat(50), "Generated by Rigcraft · rigcraft.app");
  return lines.join("\n");
}

// ─── GlassCard ────────────────────────────────────────────────────────────────

function GlassCard({ children, style, hover = false }) {
  const [isHovered, setIsHovered] = useState(false);
  return (
    <div
      style={{
        background: "rgba(20,18,16,0.7)",
        backdropFilter: "blur(12px)",
        border: "1px solid rgba(255,255,255,0.08)",
        borderRadius: 24,
        padding: 24,
        transition: "all 0.3s cubic-bezier(0.4,0,0.2,1)",
        transform: hover && isHovered ? "translateY(-4px)" : "none",
        boxShadow: hover && isHovered
          ? "0 20px 40px -15px rgba(240,165,0,0.3), 0 0 0 1px rgba(240,165,0,0.2)"
          : "0 10px 30px -15px rgba(0,0,0,0.5)",
        ...style,
      }}
      onMouseEnter={() => hover && setIsHovered(true)}
      onMouseLeave={() => hover && setIsHovered(false)}
    >
      {children}
    </div>
  );
}

function GradientText({ children, style }) {
  return (
    <span style={{
      background: "linear-gradient(135deg,#f0a500,#ffd966,#f0a500)",
      WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent",
      backgroundClip: "text", fontWeight: 800, ...style,
    }}>
      {children}
    </span>
  );
}

// ─── DonutChart ───────────────────────────────────────────────────────────────

function DonutChart({ components }) {
  const order = ["cpu", "gpu", "motherboard", "ram", "storage"];
  const items = order
    .filter((k) => components[k])
    .map((k) => ({
      key: k,
      price: Number(components[k].Price || components[k].price || 0),
      color: COMP_COLORS[k],
      icon: COMP_ICONS[k],
      name: components[k].Name || components[k].name || k,
    }))
    .filter((i) => i.price > 0);

  const total = items.reduce((s, i) => s + i.price, 0);
  if (!total) return null;

  const cx = 90, cy = 90, r = 70, strokeW = 20;
  const circumference = 2 * Math.PI * r;
  let cumulativeOffset = 0;

  const segments = items.map((item) => {
    const pct  = item.price / total;
    const dash = pct * circumference;
    const seg  = { ...item, pct, dash, gap: circumference - dash, offset: cumulativeOffset };
    cumulativeOffset += dash;
    return seg;
  });

  const [hovered, setHovered] = useState(null);
  const active = hovered !== null ? items[hovered] : null;

  return (
    <div style={{ background: "rgba(0,0,0,0.2)", borderRadius: 20, padding: 20, marginTop: 20 }}>
      <div style={{ fontSize: 12, letterSpacing: 2, color: "#888", fontFamily: "'Space Mono', monospace", marginBottom: 16 }}>
        BUDGET BREAKDOWN
      </div>
      <div style={{ display: "flex", alignItems: "center", gap: 24, flexWrap: "wrap" }}>
        {/* SVG donut */}
        <div style={{ position: "relative", flexShrink: 0 }}>
          <svg width={180} height={180}>
            {segments.map((seg, i) => (
              <circle
                key={seg.key}
                cx={cx} cy={cy} r={r}
                fill="none"
                stroke={seg.color}
                strokeWidth={hovered === i ? strokeW + 4 : strokeW}
                strokeDasharray={`${seg.dash} ${seg.gap}`}
                strokeDashoffset={-seg.offset + circumference / 4}
                style={{ cursor: "pointer", transition: "stroke-width 0.2s" }}
                onMouseEnter={() => setHovered(i)}
                onMouseLeave={() => setHovered(null)}
              />
            ))}
          </svg>
          <div style={{
            position: "absolute", top: "50%", left: "50%",
            transform: "translate(-50%,-50%)", textAlign: "center",
          }}>
            {active ? (
              <>
                <div style={{ fontSize: 11, color: active.color, fontFamily: "'Space Mono', monospace" }}>
                  {active.icon}
                </div>
                <div style={{ fontSize: 13, fontWeight: 700, color: "#fff", fontFamily: "'Space Mono', monospace" }}>
                  {(active.pct * 100).toFixed(0)}%
                </div>
              </>
            ) : (
              <>
                <div style={{ fontSize: 10, color: "#555", fontFamily: "'Space Mono', monospace", letterSpacing: 1 }}>
                  TOTAL
                </div>
                <div style={{ fontSize: 14, fontWeight: 700, color: "#f0c040", fontFamily: "'Space Mono', monospace" }}>
                  ₹{formatINR(total)}
                </div>
              </>
            )}
          </div>
        </div>

        {/* Legend */}
        <div style={{ flex: 1, minWidth: 120 }}>
          {items.map((item, i) => (
            <div
              key={item.key}
              onMouseEnter={() => setHovered(i)}
              onMouseLeave={() => setHovered(null)}
              style={{
                display: "flex", alignItems: "center", gap: 8,
                marginBottom: 8, cursor: "pointer",
                opacity: hovered !== null && hovered !== i ? 0.4 : 1,
                transition: "opacity 0.2s",
              }}
            >
              <div style={{ width: 8, height: 8, borderRadius: "50%", background: item.color, flexShrink: 0 }} />
              <div style={{ flex: 1, fontSize: 12, color: "#aaa", fontFamily: "'DM Sans', sans-serif" }}>
                {item.key.toUpperCase()}
              </div>
              <div style={{ fontSize: 12, color: "#fff", fontFamily: "'Space Mono', monospace" }}>
                ₹{formatINR(item.price)}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─── ComponentRow ──────────────────────────────────────────────────────────────

function ComponentRow({ compKey, comp }) {
  const [expanded, setExpanded] = useState(false);
  const price  = Number(comp.Price || comp.price || 0);
  const specs  = comp.specs || {};
  const hasSpecs = Object.keys(specs).length > 0;
  const color  = COMP_COLORS[compKey] || "#888";

  return (
    <div
      onClick={() => hasSpecs && setExpanded((e) => !e)}
      style={{
        background: "rgba(255,255,255,0.02)",
        border: `1px solid rgba(255,255,255,0.06)`,
        borderRadius: 16,
        padding: "16px 20px",
        marginBottom: 12,
        cursor: hasSpecs ? "pointer" : "default",
        transition: "all 0.2s",
        borderLeft: `3px solid ${color}`,
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
        {/* Icon */}
        <div style={{
          width: 40, height: 40, borderRadius: 10,
          background: `${color}18`,
          display: "flex", alignItems: "center", justifyContent: "center",
          fontSize: 18, flexShrink: 0,
        }}>
          {COMP_ICONS[compKey]}
        </div>

        {/* Name + label */}
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 11, color: color, fontFamily: "'Space Mono', monospace", letterSpacing: 1.5, marginBottom: 4 }}>
            {compKey.toUpperCase()}
          </div>
          <div style={{ fontSize: 14, color: "#e8e0d0", fontFamily: "'DM Sans', sans-serif", fontWeight: 500, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
            {comp.Name || comp.name || "—"}
          </div>
        </div>

        {/* Price */}
        <div style={{ textAlign: "right", flexShrink: 0 }}>
          <div style={{ fontSize: 16, fontWeight: 700, color: "#f0c040", fontFamily: "'Space Mono', monospace" }}>
            ₹{formatINR(price)}
          </div>
          {hasSpecs && (
            <div style={{ fontSize: 10, color: "#555", marginTop: 3 }}>
              {expanded ? "▲ hide" : "▼ specs"}
            </div>
          )}
        </div>
      </div>

      {/* Specs drawer */}
      {expanded && hasSpecs && (
        <div style={{
          marginTop: 14, paddingTop: 14,
          borderTop: "1px solid rgba(255,255,255,0.05)",
          display: "flex", flexWrap: "wrap", gap: 8,
          animation: "fadeIn 0.2s ease",
        }}>
          {Object.entries(specs).map(([k, v]) => (
            <div key={k} style={{
              background: "rgba(255,255,255,0.04)", borderRadius: 6,
              padding: "4px 10px", fontSize: 11,
              fontFamily: "'Space Mono', monospace", color: "#888",
            }}>
              <span style={{ color: "#555" }}>{k}: </span>
              <span style={{ color: "#bbb" }}>{v}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ─── BuildResult ──────────────────────────────────────────────────────────────

function BuildResult({ result, onCopy, copied }) {
  const components = result?.build?.components || {};
  const order      = ["cpu", "gpu", "motherboard", "ram", "storage"];

  return (
    <div style={{ animation: "fadeIn 0.4s ease" }}>
      {/* Header badges */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20, flexWrap: "wrap", gap: 10 }}>
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
          {result.intent && (
            <span style={{ background: "rgba(240,165,0,0.12)", border: "1px solid rgba(240,165,0,0.3)", borderRadius: 20, padding: "4px 12px", fontSize: 11, color: "#f0a500", fontFamily: "'Space Mono', monospace", letterSpacing: 1 }}>
              {result.intent}
            </span>
          )}
          {result.tier && (
            <span style={{ background: "rgba(100,220,130,0.10)", border: "1px solid rgba(100,220,130,0.25)", borderRadius: 20, padding: "4px 12px", fontSize: 11, color: "#64dc82", fontFamily: "'Space Mono', monospace", letterSpacing: 1 }}>
              {result.tier}
            </span>
          )}
          {result.build?.ai_generated && (
            <span style={{ background: "rgba(124,106,247,0.10)", border: "1px solid rgba(124,106,247,0.25)", borderRadius: 20, padding: "4px 12px", fontSize: 11, color: "#7c6af7", fontFamily: "'Space Mono', monospace", letterSpacing: 1 }}>
              🤖 AI
            </span>
          )}
        </div>
        <button
          onClick={onCopy}
          style={{
            background: copied ? "rgba(100,220,130,0.15)" : "rgba(255,255,255,0.04)",
            border: `1px solid ${copied ? "rgba(100,220,130,0.3)" : "rgba(255,255,255,0.1)"}`,
            borderRadius: 8, padding: "6px 14px",
            color: copied ? "#64dc82" : "#888",
            fontFamily: "'Space Mono', monospace", fontSize: 11,
            cursor: "pointer", transition: "all 0.2s",
          }}
        >
          {copied ? "✓ Copied" : "⎘ Copy Build"}
        </button>
      </div>

      {/* Component rows */}
      {order.map((k) => components[k] && (
        <ComponentRow key={k} compKey={k} comp={components[k]} />
      ))}

      {/* PSU + Cabinet */}
      {(result.psu_wattage || result.cabinet_type) && (
        <div style={{
          display: "flex", gap: 12, marginTop: 4, marginBottom: 4, flexWrap: "wrap",
        }}>
          {result.psu_wattage && (
            <div style={{ flex: 1, background: "rgba(255,159,75,0.08)", border: "1px solid rgba(255,159,75,0.2)", borderRadius: 12, padding: "12px 16px" }}>
              <div style={{ fontSize: 10, color: "#ff9f4b", fontFamily: "'Space Mono', monospace", letterSpacing: 1, marginBottom: 4 }}>PSU</div>
              <div style={{ fontSize: 13, color: "#e8e0d0" }}>{result.psu_wattage}</div>
            </div>
          )}
          {result.cabinet_type && (
            <div style={{ flex: 1, background: "rgba(167,139,250,0.08)", border: "1px solid rgba(167,139,250,0.2)", borderRadius: 12, padding: "12px 16px" }}>
              <div style={{ fontSize: 10, color: "#a78bfa", fontFamily: "'Space Mono', monospace", letterSpacing: 1, marginBottom: 4 }}>CASE</div>
              <div style={{ fontSize: 13, color: "#e8e0d0" }}>{result.cabinet_type}</div>
            </div>
          )}
        </div>
      )}

      {/* Donut chart */}
      <DonutChart components={components} />
    </div>
  );
}

// ─── Main App ─────────────────────────────────────────────────────────────────

export default function App() {
  const { user, logout } = useAuth();

  const [query,         setQuery]         = useState("");
  const [budget,        setBudget]        = useState(80000);
  const [displayBudget, setDisplayBudget] = useState(80000);
  const [resolution,    setResolution]    = useState("1080p");
  const [loading,       setLoading]       = useState(false);
  const [result,        setResult]        = useState(null);
  const [error,         setError]         = useState("");
  const [copied,        setCopied]        = useState(false);

  const resultRef  = useRef(null);
  const budgetTimer = useRef(null);

  // Debounce budget display
  const handleBudgetChange = useCallback((val) => {
    setBudget(val);
    clearTimeout(budgetTimer.current);
    budgetTimer.current = setTimeout(() => setDisplayBudget(val), 50);
  }, []);

  useEffect(() => {
    setDisplayBudget(budget);
  }, [budget]);

  if (!user) return <AuthPage />;

  const hasComponents = !!(
    result?.build?.components?.cpu ||
    result?.build?.components?.gpu
  );

  const handleSubmit = async () => {
    if (!query.trim() || loading) return;
    setLoading(true);
    setError("");
    setResult(null);

    try {
      const res  = await fetch(`${API_BASE}/api/recommend`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: query.trim(), budget, resolution }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail || "Request failed");
      setResult(data);
      setTimeout(() => resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 100);
    } catch (e) {
      setError(e.message || "Something went wrong. Is the backend running?");
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!result) return;
    navigator.clipboard.writeText(getBuildText(result)).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Syne:wght@700;800&family=Space+Mono:wght@400;700&family=DM+Sans:wght@400;500;600&display=swap');

        *, *::before, *::after { box-sizing: border-box; }
        body { margin: 0; background: #0d0b08; color: #e8e0d0; }

        @keyframes fadeIn  { from { opacity:0; transform:translateY(8px);  } to { opacity:1; transform:translateY(0); } }
        @keyframes fadeUp  { from { opacity:0; transform:translateY(20px); } to { opacity:1; transform:translateY(0); } }
        @keyframes spin    { to { transform: rotate(360deg); } }
        @keyframes pulse   { 0%,100% { opacity:0.4; } 50% { opacity:0.7; } }
        @keyframes glow    { 0%,100% { box-shadow: 0 0 20px rgba(240,165,0,0.1); } 50% { box-shadow: 0 0 40px rgba(240,165,0,0.2); } }

        input[type=range] {
          -webkit-appearance: none; appearance: none;
          width: 100%; height: 4px;
          background: rgba(255,255,255,0.08); border-radius: 2px; outline: none;
        }
        input[type=range]::-webkit-slider-thumb {
          -webkit-appearance: none; width: 18px; height: 18px;
          border-radius: 50%; background: #f0a500; cursor: pointer;
          box-shadow: 0 0 0 4px rgba(240,165,0,0.15);
        }

        .intent-btn:hover  { border-color: rgba(240,165,0,0.3) !important; color: #e8e0d0 !important; background: rgba(240,165,0,0.06) !important; }
        .preset-btn:hover  { border-color: rgba(240,165,0,0.4) !important; color: #f0a500 !important; }
        .submit-btn:hover:not(:disabled) { transform: translateY(-2px) !important; box-shadow: 0 12px 32px rgba(240,165,0,0.35) !important; }
        .res-btn:hover     { border-color: rgba(240,165,0,0.3) !important; color: #e8e0d0 !important; }
      `}</style>

      {/* Ambient background */}
      <div style={{ position: "fixed", inset: 0, pointerEvents: "none", zIndex: 0 }}>
        <div style={{ position: "absolute", width: 600, height: 600, top: "-10%", left: "50%", transform: "translateX(-50%)", background: "radial-gradient(circle, rgba(240,140,0,0.04) 0%, transparent 70%)" }} />
        <div style={{ position: "absolute", width: 400, height: 400, bottom: "10%", right: "10%", background: "radial-gradient(circle, rgba(124,106,247,0.03) 0%, transparent 70%)" }} />
      </div>

      <div style={{ position: "relative", zIndex: 1, maxWidth: 780, margin: "0 auto", padding: "24px 20px 60px" }}>

        {/* ── Header ── */}
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 40, animation: "fadeUp 0.5s ease" }}>
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
              <span style={{ fontSize: 22 }}>⚡</span>
              <span style={{ fontFamily: "'Syne', sans-serif", fontWeight: 800, fontSize: 20, letterSpacing: 3, color: "#fff" }}>RIGCRAFT</span>
            </div>
            <div style={{ fontSize: 10, color: "#444", fontFamily: "'Space Mono', monospace", letterSpacing: 2, marginTop: 2 }}>
              PC BUILD RECOMMENDATION ENGINE
            </div>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <span style={{ fontSize: 12, color: "#555", fontFamily: "'Space Mono', monospace" }}>
              {user.username || user.email?.split("@")[0]}
            </span>
            <button onClick={logout} style={{
              background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)",
              borderRadius: 8, padding: "6px 14px", color: "#666",
              fontFamily: "'Space Mono', monospace", fontSize: 11, cursor: "pointer", letterSpacing: 1,
              transition: "all 0.2s",
            }}>
              LOGOUT
            </button>
          </div>
        </div>

        {/* ── Hero ── */}
        <div style={{ textAlign: "center", marginBottom: 40, animation: "fadeUp 0.6s ease" }}>
          <h1 style={{ fontFamily: "'Syne', sans-serif", fontWeight: 800, fontSize: "clamp(28px, 6vw, 46px)", margin: "0 0 12px", lineHeight: 1.1 }}>
            Build Your Perfect<br />
            <GradientText>PC Rig</GradientText>
          </h1>
          <p style={{ color: "#555", fontSize: 14, fontFamily: "'DM Sans', sans-serif", margin: 0 }}>
            AI-powered recommendations. Indian market prices. Instant compatibility checks.
          </p>
        </div>

        {/* ── Input card ── */}
        <GlassCard style={{ marginBottom: 24, animation: "fadeUp 0.7s ease" }}>

          {/* Intent selector */}
          <div style={{ marginBottom: 28 }}>
            <div style={{ fontSize: 12, color: "#555", fontFamily: "'Space Mono', monospace", letterSpacing: 2, marginBottom: 14 }}>
              🎯 USE CASE
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))", gap: 8 }}>
              {INTENTS.map((intent) => (
                <button
                  key={intent.label}
                  className="intent-btn"
                  onClick={() => setQuery(intent.label)}
                  style={{
                    background: query === intent.label ? "rgba(240,165,0,0.12)" : "rgba(255,255,255,0.02)",
                    border: `1px solid ${query === intent.label ? "rgba(240,165,0,0.4)" : "rgba(255,255,255,0.07)"}`,
                    borderRadius: 12, padding: "10px 12px", cursor: "pointer",
                    transition: "all 0.2s", textAlign: "left",
                  }}
                >
                  <div style={{ fontSize: 16, marginBottom: 4 }}>{intent.icon}</div>
                  <div style={{ fontSize: 12, fontWeight: 600, color: query === intent.label ? "#f0a500" : "#aaa", fontFamily: "'DM Sans', sans-serif" }}>
                    {intent.label}
                  </div>
                  <div style={{ fontSize: 10, color: "#444", fontFamily: "'DM Sans', sans-serif", marginTop: 2 }}>
                    {intent.description}
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Custom query */}
          <div style={{ marginBottom: 28 }}>
            <div style={{ fontSize: 12, color: "#555", fontFamily: "'Space Mono', monospace", letterSpacing: 2, marginBottom: 10 }}>
              ✏️ OR DESCRIBE YOUR NEEDS
            </div>
            <input
              type="text"
              placeholder='e.g. "I want to play Valorant at 240fps and stream on Twitch"'
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
              style={{
                width: "100%", background: "rgba(255,255,255,0.03)",
                border: "1px solid rgba(255,255,255,0.1)", borderRadius: 14,
                padding: "14px 18px", color: "#fff", fontSize: 14, outline: "none",
                transition: "all 0.2s", fontFamily: "'DM Sans', sans-serif",
              }}
              onFocus={(e)  => e.target.style.borderColor = "#f0a500"}
              onBlur={(e)   => e.target.style.borderColor = "rgba(255,255,255,0.1)"}
            />
          </div>

          {/* Budget */}
          <div style={{ marginBottom: 28 }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}>
              <div style={{ fontSize: 12, color: "#555", fontFamily: "'Space Mono', monospace", letterSpacing: 2 }}>
                💰 BUDGET
              </div>
              <div style={{ fontSize: 22, fontWeight: 800, color: "#f0c040", fontFamily: "'Space Mono', monospace" }}>
                ₹{formatINR(displayBudget)}
              </div>
            </div>

            <div style={{ display: "flex", gap: 8, marginBottom: 18, flexWrap: "wrap" }}>
              {BUDGET_PRESETS.map((p) => (
                <button
                  key={p.value}
                  className="preset-btn"
                  onClick={() => { setBudget(p.value); setDisplayBudget(p.value); }}
                  style={{
                    background: budget === p.value ? "rgba(240,165,0,0.15)" : "rgba(255,255,255,0.03)",
                    border: `1px solid ${budget === p.value ? "rgba(240,165,0,0.5)" : "rgba(255,255,255,0.08)"}`,
                    borderRadius: 30, padding: "7px 16px",
                    color: budget === p.value ? "#f0a500" : "#666",
                    fontSize: 12, cursor: "pointer", transition: "all 0.2s",
                    fontFamily: "'Space Mono', monospace",
                  }}
                >
                  {p.label}
                </button>
              ))}
            </div>

            <input type="range" min="10000" max="400000" step="5000"
              value={budget} onChange={(e) => handleBudgetChange(Number(e.target.value))}
            />
            <div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: "#444", marginTop: 6, fontFamily: "'Space Mono', monospace" }}>
              <span>₹10,000</span><span>₹4,00,000</span>
            </div>
          </div>

          {/* Resolution */}
          <div style={{ marginBottom: 28 }}>
            <div style={{ fontSize: 12, color: "#555", fontFamily: "'Space Mono', monospace", letterSpacing: 2, marginBottom: 14 }}>
              🖥️ TARGET RESOLUTION
            </div>
            <div style={{ display: "flex", gap: 10 }}>
              {RESOLUTIONS.map((r) => (
                <button key={r} className="res-btn"
                  onClick={() => setResolution(r)}
                  style={{
                    flex: 1,
                    background: resolution === r ? "linear-gradient(135deg,rgba(240,165,0,0.2),rgba(240,165,0,0.08))" : "rgba(255,255,255,0.03)",
                    border: `1px solid ${resolution === r ? "rgba(240,165,0,0.5)" : "rgba(255,255,255,0.08)"}`,
                    borderRadius: 12, padding: "12px",
                    color: resolution === r ? "#f0a500" : "#666",
                    fontSize: 13, fontWeight: 600, cursor: "pointer", transition: "all 0.2s",
                    fontFamily: "'Space Mono', monospace",
                  }}
                >
                  {r}
                </button>
              ))}
            </div>
          </div>

          {/* Submit */}
          <button
            className="submit-btn"
            onClick={handleSubmit}
            disabled={loading || !query.trim()}
            style={{
              width: "100%",
              background: loading ? "rgba(240,165,0,0.2)" : "linear-gradient(135deg,#f0a500,#ffb82e)",
              border: "none", borderRadius: 16, padding: "18px",
              color: loading ? "#f0a500" : "#0a0a0a",
              fontSize: 15, fontWeight: 800, cursor: loading ? "not-allowed" : "pointer",
              transition: "all 0.25s", opacity: loading ? 0.9 : 1,
              fontFamily: "'Syne', sans-serif", letterSpacing: 1,
            }}
          >
            {loading ? (
              <span style={{ fontSize: 13, fontFamily: "'Space Mono', monospace", letterSpacing: 1 }}>
                Optimizing...
              </span>
            ) : (
              <span>⚡ Generate Build</span>
            )}
          </button>
        </GlassCard>

        {/* Error */}
        {error && (
          <div style={{
            background: "rgba(239,68,68,0.08)", border: "1px solid rgba(239,68,68,0.25)",
            borderRadius: 16, padding: "16px 20px", marginBottom: 24,
            color: "#ef4444", animation: "fadeIn 0.3s ease",
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
              <span style={{ fontSize: 18 }}>⚠️</span>
              <div>
                <div style={{ fontWeight: 600, marginBottom: 2, fontFamily: "'DM Sans', sans-serif" }}>Error</div>
                <div style={{ fontSize: 13, color: "#ff8888", fontFamily: "'DM Sans', sans-serif" }}>{error}</div>
              </div>
            </div>
          </div>
        )}

        {/* ── Loading — show the bouncing ball Loader ── */}
        {loading && (
          <GlassCard style={{ marginBottom: 24 }}>
            <Loader label="Optimizing your build..." />
          </GlassCard>
        )}

        {/* Result */}
        <div ref={resultRef}>
          {!loading && result && (
            <GlassCard style={{ animation: "fadeIn 0.5s ease" }}>
              {hasComponents ? (
                <BuildResult result={result} onCopy={handleCopy} copied={copied} />
              ) : (
                <div>
                  <div style={{ fontSize: 11, color: "#f0a500", fontFamily: "'Space Mono', monospace", letterSpacing: 2, marginBottom: 14 }}>
                    📋 RECOMMENDATION
                  </div>
                  <div style={{ fontSize: 14, color: "#ccc", lineHeight: 1.8, fontFamily: "'DM Sans', sans-serif", whiteSpace: "pre-wrap" }}>
                    {result.message}
                  </div>
                </div>
              )}
            </GlassCard>
          )}
        </div>

        {/* AI Panel */}
        {!loading && result && hasComponents && (
          <AIPanel result={result} />
        )}

        {/* Footer */}
        <div style={{
          textAlign: "center", marginTop: 60, padding: "20px 0",
          borderTop: "1px solid rgba(255,255,255,0.04)",
          color: "#333", fontSize: 10, fontFamily: "'Space Mono', monospace", letterSpacing: 2,
        }}>
          RIGCRAFT · PC BUILD RECOMMENDATION ENGINE · ALL PRICES IN INR
        </div>
      </div>
    </>
  );
}